#+TITLE: Tools

This is just a list of the tools we're using and creating
* Communication and Collaboration
We've been collaborating via [[http://www.slack.com][Slack]] and [[http://github.com][Github]]. If you're not already familiar with these tools, and have time to check them out, please do so!
* Chrome Extension

The EOT project has a simple bookmarklet for nominating "seeds" for their webcrawler; you can [[http://digital2.library.unt.edu/nomination/eth2016/about/][read about it here]]. For our event we derived a [[https://github.com/CivicTechTO/presidential-harvest-nomination-tool][Chrome Extension]], and would recommend its use to future groups.
* Scrapers
We expectto use [[https://scrapy.org/][the scrapy Python library]] and maybe its GUI companion [[https://scrapinghub.com/portia/][portia]] for this work.
* Crawlers
:PROPERTIES:
:CUSTOM_ID: crawlers
:END:
The IA uses [[http://crawler.archive.org/index.html][Heritrix]] for its crawl, but it is a little finicky to set up and somewhat complex to learn to use, so we are not using it at our event.  Instead, we will have to code our own.  THere are basically two technical specifications:
- any tool we use should respect robots.txt
- Any archives we produce should be in WARC format, the ISO standard for web archives used by the Internet Archive.  

One simple solution seems to be [[https://github.com/odie5533/WarcMiddleware][WARC Middleware]], which can accept a list of URL's in a file.  As I understand it Scrapy obeys robots.txt if the variable assignment ~ROBOTSTXT_OBEY = True~ is included in the file.

Another suggestion we've gotten is [[https://github.com/ludios/grab-site][grab-site]], which came to us via the maintainers of [[https://webrecorder.io/][webrecorder]].  

You can learn more about the WARC here:
- [[http://www.archiveteam.org/index.php?title=The_WARC_Ecosystem][WARC Ecosystem]]
- [[https://www.taricorp.net/2016/web-history-warc/][collecting browsing history]]
- [[https://github.com/dhamaniasad/WARCTools][List of WARC tools]]
* Server Architecture
We have an offer of help from the maintainer of [[https://github.com/ipfs/ipfs][IPFS]]. [[https://github.com/ipfs/community/blob/master/articles/endangered-data.md][Here's some background on the protocol]]. 
